# Este es el repositorio de donde se obtiene el hook para formatear el código .NET
repos:
  - repo: https://github.com/dotnet/format
    # Esta es la versión del hook que se está utilizando
    rev: v8.0.453106
    hooks:
      # Este hook formatea el código .NET antes de cada commit
      - id: dotnet-format
        name: Format .NET project

  # Estos son hooks locales, definidos específicamente para este repositorio
  - repo: local
    hooks:
      # Este hook construye el proyecto API antes de cada commit
      - id: dotnet-build-api
        name: Build API project
        entry: dotnet build ./ApiCreditSimulator.Api/ApiCreditSimulator.Api.csproj
        language: system
        # Este hook se ejecuta solo cuando se modifican los archivos .cs en el directorio ApiCreditSimulator.Api
        files: '^ApiCreditSimulator\.Api/.*\.cs$'
        pass_filenames: false

      # Este hook construye el proyecto Access antes de cada commit
      - id: dotnet-build-access
        name: Build Access project
        entry: dotnet build ./ApiCreditSimulator.Access/ApiCreditSimulator.Access.csproj
        language: system
        # Este hook se ejecuta solo cuando se modifican los archivos .cs en el directorio ApiCreditSimulator.Access
        files: '^ApiCreditSimulator\.Access/.*\.cs$'
        pass_filenames: false

      # Este hook construye el proyecto Shared antes de cada commit
      - id: dotnet-build-shared
        name: Build Shared project
        entry: dotnet build ./ApiCreditSimulator.Shared/ApiCreditSimulator.Shared.csproj
        language: system
        # Este hook se ejecuta solo cuando se modifican los archivos .cs en el directorio ApiCreditSimulator.Shared
        files: '^ApiCreditSimulator\.Shared/.*\.cs$'
        pass_filenames: false

      # Este hook verifica las dependencias .NET desactualizadas antes de cada commit
      - id: dotnet-outdated
        name: Check for outdated .NET dependencies
        entry: dotnet outdated
        language: system
        # Este hook se ejecuta solo cuando se modifican los archivos .csproj o .config
        files: '\.(csproj|config)$'
        pass_filenames: false

      # Este hook ejecuta las pruebas unitarias antes de cada commit
      - id: dotnet-test
        name: Run .NET unit tests
        entry: dotnet test ApiCreditSimulator.Tests/ApiCreditSimulator.Tests.csproj
        language: system
        # Este hook se ejecuta solo cuando se modifican los archivos .cs en el directorio ApiCreditSimulator.Tests
        files: '.*\.cs$'
        pass_filenames: false